name: Daily Task

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Generate
        uses: Platane/snk@main
        with:
          github_user_name: tecnicocefet
          outputs: |
            ./assets/github-contribution-grid-snake.gif
            ./assets/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
